<?php

/**
 * @file
 * Install, update and uninstall functions for the sasha-cat module.
 */

/**
 * Implements hook_theme().
 */
function sasha_cat_theme($existing, $type, $theme, $path) {
  return [
    'sasha_cat_page' => [
      'variables' => [
        'cat_form' => NULL,
        'cat_table' => [],
      ],
    ],
    'sasha_cat_table' => [
      'variables' => [
        'cats' => [],
      ],
    ],
  ];
}
